import { supabaseAdmin } from '../../config/supabase'

export async function getActiveBanners() {
  const { data, error } = await supabaseAdmin
    .from('notifications')
    .select('*')
    .in('type', ['Login Banner', 'Universal Announcement'])
    .eq('status', 'sent')
    .order('created_at', { ascending: false })
    .limit(1) // Just get the latest one

  if (error) throw error
  return data?.[0] || null
}

// Every notification an admin sends (any of the 6 broadcast types) PLUS
// this user's own personal notifications (welcome/winning/deposit/withdraw/
// referral, generated by the DB triggers in schema.sql) — merged into one
// feed, sorted by recency, so the single bell shows everything relevant to
// this person rather than only admin broadcasts.
export async function getNotificationsFeed(limit: number = 20, userId?: string | null) {
  const { data: broadcasts, error: broadcastErr } = await supabaseAdmin
    .from('notifications')
    .select('*')
    .eq('status', 'sent')
    .order('created_at', { ascending: false })
    .limit(limit)

  if (broadcastErr) throw broadcastErr

  let personal: any[] = []
  if (userId) {
    const { data, error: personalErr } = await supabaseAdmin
      .from('user_notifications')
      .select('*')
      .eq('user_id', userId)
      .order('created_at', { ascending: false })
      .limit(limit)

    if (personalErr) throw personalErr
    // Normalize to the same shape the frontend already expects from the
    // broadcast table (title/content/type/created_at/link_url), so
    // NotificationCenter doesn't need two different rendering paths.
    personal = (data || []).map((n) => ({
      id: n.id,
      title: n.title,
      content: n.content,
      type: n.type,
      link_url: n.link_url,
      status: 'sent',
      created_at: n.created_at,
    }))
  }

  return [...(broadcasts || []), ...personal]
    .sort((a, b) => new Date(b.created_at).getTime() - new Date(a.created_at).getTime())
    .slice(0, limit)
}

export async function registerPushToken(userId: string, subscription: any, deviceType: string = 'web') {
  const token = typeof subscription === 'string' ? subscription : JSON.stringify(subscription);
  
  const { error } = await supabaseAdmin
    .from('push_tokens')
    .upsert({
      user_id: userId,
      token,
      device_type: deviceType,
      created_at: new Date().toISOString()
    }, { onConflict: 'token' })

  if (error) throw error
  return { success: true }
}